### ISSUE TITLE
Can't add .ZIP to Arduino IDE.

### ISSUE THREAD

**Issue by ghost** [chegewara/esp32-usb-v2#7]
![image](https://github.com/chegewara/esp32-usb-v2/assets/67878277/5c2d0532-92a3-44e3-8c23-2a3575287d40)

Directly installed from the github and attempted to put it in.

**Comment by chegewara** [comment]
Im not sure, but maybe missing some files required by arduino, like `library.properties`

**Comment by ghost** [comment]
Yup, that was it, I just copied and pasted some random ones and modified it a little
